### ISSUE TITLE
Meta_custom not defined if loaded after wheelhouse-page-fragments

### ISSUE THREAD

**Issue by williamgkzhang** [WheelhouseCMS/wheelhouse-meta-tags#1]
I'm using this plugin and also WheelhouseCMS/wheelhouse-page-fragments.  If wheelhouse-page-fragments is specified before this plugin in the Gemile, meta_custom does not get defined.  Works fine if  meta-tags is loaded before page-fragments though.

**Comment by spohlenz** [comment]
Hi @williamgkzhang. I can confirm that I am able to reproduce this. Not sure yet why that's happening but I'll get to the bottom of it.

**Comment by spohlenz** [comment]
With the current extension framework, I'm not sure if I can provide a better solution other than to include `wheelhouse-meta-tags` before `wheelhouse-page-fragments` in your Gemfile.

Please let me know if you encounter any issues in doing it this way.
